#pragma config(Motor,  port2,           flWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           blWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           brWheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#define SKILLS_PRGM

//#define RKCOMP_DEBUG

#include "rkUtil/lib.h"

#include "rkControl/base.h"
#include "rkControl/pid.h"

#include "botConfig.h"
#include "driverConfig.h"

#ifdef LCD
#define RKCOMP_LCD

#include "rkLcd/lib.h"
#endif

#include "rkCompetition/lib.h"

#include "common.h"

#include "auton.h"
#include "drive.h"

#ifdef LCD
#include "lcd.h"
#endif
